- packages/ui/src/Grid/Grid.stories.tsx
- packages/ui/src/Grid/Grid.tsx
- packages/ui/src/Grid/index.ts
- packages/ui/src/Grid/styled.tsx
- packages/ui/src/Grid/types.ts
https://github.com/kaluga-astral/frontend/pull/40
> UIKIT-75 - Реализация Grid

- packages/ui/src/Tag/Tag.stories.tsx
- packages/ui/src/Tag/Tag.tsx
- packages/ui/src/Tag/constants.ts
- packages/ui/src/Tag/index.ts
- packages/ui/src/Tag/styled.tsx
- packages/ui/src/Tag/types.ts
Пересоздал ветку после того как её сломал 
https://github.com/kaluga-astral/frontend/pull/35 исправил ошибки которые были описаны тут
> UIKIT-49 - Готовый компонент Tag + правки по PR 35

- package.json
- packages/fonts/package.json
- packages/icons/package.json
- packages/ui/package.json
> @astral/icons. Убран files из package.json

- .eslintignore
- .eslintrc
- CONTRIBUTING.md
- package.json
- packages/icons/tsconfig.json
- packages/icons/tsconfig.lint.json
- packages/ui/tsconfig.json
- packages/ui/tsconfig.lint.json
- Исправлены include и exclude в tsconfig.json
- Добавлен ignorePatterns в .eslintrc
- Исправлен корневой скрипт lint
> chore: изменены конфигурационные файлы ts и eslint

- packages/ui/src/Autocomplete/Autocomplete.stories.tsx
- packages/ui/src/Autocomplete/Autocomplete.tsx
- packages/ui/src/theme/components/MuiAutocomplete.ts
- packages/ui/src/theme/components/MuiButtonBase.ts
- packages/ui/src/theme/components/components.ts
UIKIT-114 Исправлено отображение кнопок в инпуте, 
UIKIT-113 Добавлен default case в storybook, 
UIKIT-115 Исправлены отступы в multiple версии, 
UIKIT-117 Добавлена обработка пустого набора options
> bug(ui, Autocomplete): Исправлено отображение тэгов, кнопок в инпуте, исправлена обработка пустого набора options

- packages/ui/src/DatePicker/DatePicker.tsx
- packages/ui/src/DatePicker/types.ts
В API пикера есть проп inputRef, подправлен тип DatePickerProps
> refactor(ui,DatePicker): убран forwardRef, поправлен тип DatePickerProps

- packages/ui/src/Typography/index.ts
В рамках фикса также ушла проблема с Typography variant (UIKIT-194)
> bug(ui,Typography): добавлен экспорт типов

- packages/ui/src/ActionCell/ActionCell.tsx
- packages/ui/src/DataGrid/DataGrid.stories.tsx
- packages/ui/src/DataGrid/DataGrid.tsx
- packages/ui/src/DataGrid/DataGridBody/DataGridBody.tsx
- packages/ui/src/DataGrid/DataGridBody/types.ts
- packages/ui/src/DataGrid/types.ts
- packages/ui/src/IconDropdownButton/IconDropdownButton.tsx
- packages/ui/src/theme/components/MuiOutlinedInput.ts
- packages/ui/src/theme/components/MuiTableRow.ts
- packages/ui/src/theme/components/components.ts
- packages/ui/src/theme/palette/palette.ts
в DataGrid был добавлен обработчик клика и ховер на строку
> UIKIT-275: feat(ui,DataGrid): Добавлен обработчик onRowClick и hover

- .github/workflows/pull_request_lint.yml
- commander/index.js
- commander/main.js
- commander/package.json
- commander/tasks/lintPRTitle.js
- package-lock.json
- package.json
Функционал дублируется в репозитории [code-style](https://github.com/kaluga-astral/code-style/pull/33), в будущем commander будет вынесен в отдельный пакет
> chore(UIKIT-335,commander): Добавлена команда для линтинга title PR 

- packages/ui/src/index.ts
глупая ошибка, пропустил экспорт, и теперь в проекте не получается использовать
> bug(UIKIT-327,ui,OverflowTypography): Добавлен экспорт комопнента

- packages/ui/src/OverflowTypography/hooks/useOverflowed/useOverflowed.ts
При билде в продакшн возникает ошибка, методом перебора удалось найти первопричину.
> bug: Исправлена ошибка при сборке пакета в production

- packages/ui/src/Typography/Typography.tsx
В Typography отстустсвует forwardRef, отчего нехватает нужного функционала
> bug(UIKIT-327,ui,Typography): Добавление forwardRef

- packages/ui/src/Tag/Tag.tsx
Добавлен forwardRef для Tag, чтобы работали тултипы на теге
> bug(UIKIT-389,ui,Tag): Добавлен forwardRef

- packages/ui/src/Alert/Alert.tsx
- packages/ui/src/Alert/styles.ts
Добавлены стили для корректного отображения на мобильных устройствах в соответствии с макетом "https://www.figma.com/file/vRYXZlzS418qlQuep8jiFd/%D0%9A%D0%AD%D0%94%D0%9E-Mobile?node-id=226%3A8629".
> chore(UIKIT-423,ui,Alert): Доработать компонент Alert

- packages/ui/src/DashboardLayout/Header/Header.tsx
У нас на админке КЭДО регистрация своя, и пока пользователь не залогинился, мы не можем генерировать что то о профиле пользователя в хедере лэйаута.
https://astraltrack.atlassian.net/browse/UIKIT-426
> bug(UIKIT-426,ui,DashboardLayout): опциональный profile

- packages/ui/src/Description/styles.ts
> feat(UIKIT-425,ui,Description): Адаптация под мобильную версию 

- packages/ui/src/Description/Name/Name.tsx
- packages/ui/src/Description/styles.ts
feat(UIKIT-428,ui,Description): Изменён размер шрифта для mobile и default цвет для Name
> feat(UIKIT-428,ui,Description): Изменён размер шрифта для mobile и default цвет для Name

- commander/constants.js
- commander/main.js
- commander/tasks/build.js
- packages/form/src/index.ts
- packages/icons/index.stories.tsx
- packages/icons/tsconfig.build.json
- packages/icons/tsconfig.json
- packages/ui/declarations/images.d.ts
- packages/ui/package.json
- packages/ui/src/ActionCell/ActionCell.stories.tsx
- packages/ui/src/ContentState/ContentState.stories.tsx
- packages/ui/src/DashboardLayout/DashboardLayout.stories.tsx
- packages/ui/src/DatePicker/DatePicker.stories.tsx
- packages/ui/src/ListItemButton/ListItemButton.tsx
- packages/ui/src/NavMenu/NavMenu.stories.tsx
- packages/ui/src/Placeholder/Placeholder.stories.tsx
- packages/ui/src/Select/Select.stories.tsx
- packages/ui/src/TextField/TextField.stories.tsx
- packages/ui/src/Typography/Typography.stories.tsx
- packages/ui/tsconfig.build.json
- packages/ui/tsconfig.json
При использовании VS Code в историях компонентов отображаются ошибка 
Было решено создать отдельный конфиг для сборки проекта
> chore: Добавлены отдельные ts-конфиги для сборки пакетов

- packages/ui/src/Button/styles.ts
- packages/ui/src/ButtonBase/styles.ts
по дизайну variant link не должен иметь паддингов
[Sirius Design System (АКТУАЛЬНО)](https://www.figma.com/file/3ghN4WjSgkKx5rETR64jqh/Sirius-Design-System-(%D0%90%D0%9A%D0%A2%D0%A3%D0%90%D0%9B%D0%AC%D0%9D%D0%9E)?node-id=156%3A1145)
https://astraltrack.atlassian.net/browse/UIKIT-436
> bug(UIKIT-436,ui,Button): Обнуление паддингов для версии link

- packages/ui/src/Placeholder/Placeholder.tsx
- packages/ui/src/Placeholder/styles.ts
https://astraltrack.atlassian.net/browse/UIKIT-437
так же нужна передача параметров для высоты и ишрины картинки
> bug(UIKIT-437,ui,Placeholder): фикс растягивания картинки

- package-lock.json
- packages/ui/package.json
- packages/ui/src/BackdropStack/hooks/useBackdropStackToggle/useBackdropStackToggle.ts
- packages/ui/src/BackdropStack/services/BackdropStackManager/BackdropStackManager.ts
При использование nanoid 4 версии, происходит ошибка в jest тестах из-за es-модулей.
> bug(UIKIT-447,ui,BackdropStack): Удален nanoid

- packages/ui/src/Grid/styled.tsx
https://astraltrack.atlassian.net/browse/UIKIT-452
> bug(UIKIT-452,ui,Grid): фикс варнинга неизвестного атрибута

- packages/form/tsconfig.build.json
- packages/form/tsconfig.json
В пакете form при билде из-за кривых деклараций некорректно формировалась структура файлов
после этих правок:
> bug(form): Исправлены declarations

- packages/ui/src/DatePicker/DatePickerInput/DatePickerInput.tsx
- packages/ui/src/MaskField/MaskField.tsx
О.Р. :
При удалении части даты, удаленная часть заменяется подчеркиванием
Ф.Р. :
При удалении части даты вся дата смещается в сторону
> bug(UIKIT-475,ui,Datepicker): Добавлено использование blocks

- packages/ui/src/DatePicker/DatePicker.stories.tsx
пул реквест для перезапуска пайплайна релиза
> bug(UIKIT-475): расширение кейсов DatePicker

- packages/ui/src/Fab/Fab.tsx
> bug(UIKIT-481,ui,Fab): фикс варнинга

- packages/ui/src/BackdropStack/BackdropStack.stories.tsx
- packages/ui/src/BackdropStack/hooks/useBackdropStackToggle/useBackdropStackToggle.ts
- packages/ui/src/BackdropStack/services/BackdropStackManager/BackdropStackManager.ts
- packages/ui/src/DatePicker/DatePicker.tsx
- packages/ui/src/DatePicker/DatePickerPopper/DatePickerPopper.tsx
- packages/ui/src/hooks/index.ts
- packages/ui/src/hooks/useEscapeClickEffect/useEscapeClickEffect.ts
- packages/ui/src/hooks/useToggle/useToggle.ts
- packages/ui/src/types.ts
Календарь не взаимодействует с Backdropstack Manager.
> bug(UIKIT-485,ui,Datepicker): добавление возможности взаимодействия c BackdropstackManager

- README.md
> feat(UIKIT-506,ui,useRadioGroup): Экспорт хука useRadioGroup

- packages/ui/src/ActionCell/ActionCell.tsx
- packages/ui/src/MenuItem/MenuItem.tsx
- packages/ui/src/MenuItem/styled.ts
- packages/ui/src/MenuItem/types.ts
- packages/ui/src/PageHeader/styles.ts
- packages/ui/src/theme/components/MuiMenuItem.ts
В рамках ПР не удержался и подрефакчил MenuItem
> bug(UIKIT-554,ui,ActionCell): добавлена возможность прокидывать пропы до контролов

- .github/workflows/ci_packages.yml
[Результат](https://github.com/kaluga-astral/frontend/actions/runs/3880590845#summary-10543497428) выполнения тестов:
> chore(UIKIT-598): Добавлен actions для отображения junit

- packages/components/src/Notification/Notification.stories.tsx
- packages/components/src/Notification/types.ts
пропущенное место где надо было переименовать пропс
> bug(UIKIT-599,ui,Notification): фикс типов для кнопки закрытия

- package.json
- packages/components/src/FlowButton/styles.ts
> bug(UIKIT-649,ui,FlowButton): Сделаны отступы в соответствии с макетом

- packages/components/src/hooks/useToggle/useToggle.test.ts
> test(UIKIT-812,ui,useToggle): Тест для useToggle

- package-lock.json
- packages/form/package.json
- packages/form/src/Form/Form.stories.tsx
- packages/form/src/FormAutocomplete/FormAutocomplete.stories.tsx
- packages/form/src/FormAutocomplete/FormAutocomplete.test.tsx
- packages/form/src/FormCheckbox/FormCheckbox.stories.tsx
- packages/form/src/FormDatePicker/FormDatePicker.stories.tsx
- packages/form/src/FormDatePicker/FormDatePicker.test.tsx
- packages/form/src/FormDatePicker/FormDatePicker.tsx
- packages/form/src/FormMaskField/FormMaskField.stories.tsx
- packages/form/src/FormMobilePhoneField/FormMobilePhoneField.stories.tsx
- packages/form/src/FormMobilePhoneField/FormMobilePhoneField.tsx
- packages/form/src/FormSelect/FormSelect.stories.tsx
- packages/form/src/FormSubmitButton/FormSubmitButton.stories.tsx
- packages/form/src/FormTextArea/FormTextArea.stories.tsx
- packages/form/src/FormTextField/FormTextField.stories.tsx
- packages/form/src/FormTextField/FormTextField.test.tsx
- packages/form/src/hooks/useFormInputProps/useFormInputProps.ts
- packages/form/src/types.ts
> feat(UIKIT-779,form): Удалены правила валидации из полей форм

- packages/components/src/Description/Description.stories.tsx
- packages/components/src/Description/Description.test.tsx
- packages/components/src/Description/Description.tsx
- packages/components/src/Description/DescriptionProvider/DescriptionProvider.tsx
- packages/components/src/Description/Name/Name.tsx
- packages/components/src/Description/constants.ts
> feat(UIKIT-570,Description): Добавлена возможность изменять разделитель компонента

- packages/components/src/DropdownButton/DropdownButton.stories.tsx
- packages/components/src/DropdownButton/DropdownButton.tsx
> chore(ui): Подтянуты последние изменения из main

- packages/components/src/Breadcrumbs/Breadcrumbs.stories.tsx
- packages/components/src/Breadcrumbs/styles.ts
> doc(UIKIT-504,ui,Breadcrumbs): Реализация сторибука Breadcrumbs

- packages/components/src/Description/Description.stories.tsx
> doc(UIKIT-631,ui,Description): Реализация сторибука Description

- packages/components/src/DashboardLayout/Sidebar/SidebarToggler/SidebarToggleButton/SidebarToggleButton.tsx
- packages/components/src/DashboardLayout/Sidebar/SidebarToggler/SidebarToggleButton/styles.ts
> bug(UIKIT-746,ui,Sidebar): Реализовано скрытие элементов через css

- packages/components/src/DashboardLayout/Sidebar/SidebarToggler/SidebarToggleButton/SidebarToggleButton.tsx
- packages/components/src/DashboardLayout/Sidebar/SidebarToggler/SidebarToggleButton/styles.ts
Откат по причине появления ui багов в NextJs
> bug(UIKIT-746,ui,Sidebar): Откат скрытия элементов через css

- packages/components/src/index.ts
> feat(UIKIT-849, ui, DateRangePicker): Добавлен export компонента

- packages/components/src/DataGrid/DataGrid.tsx
- packages/components/src/DataGrid/DataGridNoData/DataGridNoData.tsx
- packages/components/src/DataGrid/DataGridNoData/styles.ts
> bug(UIKIT-850,ui,DataGrid): Исправлена семантика верстки

- packages/components/src/Select/Select.test.tsx
- packages/components/src/Select/Select.tsx
> feat(UIKIT-858,ui,Select): Добавлен forwardRef для Select

- package-lock.json
- packages/components/src/DatePicker/DatePicker.tsx
- packages/components/src/DatePicker/DatePickerInput/DatePickerInput.tsx
- packages/components/src/DateRangePicker/DateRangePicker.tsx
> feat(UIKIT-862, ui, DatePicker, DateRangePicker): Добавлен prop size

- packages/components/src/Checkbox/styles.ts
> bug(UIKIT-535,ui,Checkbox): Исправлено отображение для Ios

- packages/components/src/DatePicker/DatePicker.tsx
> refactor(UIKIT-706,ui,DatePicker): Добавлен проп inputRef

- packages/components/src/Fab/Fab.stories.tsx
> doc(UIKIT-794,ui,Fab): Реализован storybook

- packages/components/src/Alert/Alert.stories.tsx
> doc(UIKIT-892,ui,Alert): Добавлена ссылка на CollapsableAlert

- packages/components/src/Stepper/StepContent/index.ts
- packages/components/src/Stepper/Stepper.stories.tsx
- packages/components/src/Stepper/index.ts
> feat(UIKIT-908, ui, Stepper): Добавлен StepContent

- package-lock.json
- package.json
- packages/components/tsconfig.build.json
- packages/features/tsconfig.build.json
- packages/form/package.json
- packages/form/src/FormRadioGroup/FormRadioGroup.test.tsx
- packages/form/tsconfig.build.json
- packages/ui/tsconfig.build.json
Из-за того, что билдились тесты и storybook в итоговый пакет могло попадать содержимое, которое ломало установку зависимостей
> build(UIKIT-851,form): Исправлена ошибка сборки пакета

- packages/icons/generated-themed-icons/CopyOutlineMd.tsx
- packages/icons/generated-themed-icons/index.ts
> feat(UIKIT-911,icons): Добавлена иконка CopyOutlineMd

- packages/form/src/FormCheckbox/FormCheckbox.stories.tsx
- packages/form/src/FormCheckbox/FormCheckbox.tsx
> feat(UIKIT-910,ui,FormCheckbox): Типизация ReactNode для title

- .storybook/themes.js
- packages/components/src/theme/constants.ts
- packages/components/src/theme/palette/brandPalette.ts
- packages/components/src/theme/palette/palette.ts
> feat(UIKIT-925,ui,theme): Добавлена цветовая палитра для бренда СБЕР

- packages/components/src/Grid/Grid.stories.tsx
- packages/components/src/Grid/styles.tsx
- packages/components/src/Grid/types.ts
> feat(UIKIT-837,ui,Grid):  Добавленна поддержка строковых значения для columns и rows

- packages/components/src/DataGrid/DataGrid.stories.tsx
- packages/components/src/DataGrid/DataGrid.tsx
- packages/components/src/DataGrid/DataGridBody/DataGridBody.tsx
- packages/components/src/theme/components/MuiTableRow.ts
> feat(UIKIT-932, ui, DataGrid): Добавлен проп activeRowId

- packages/icons/generated-themed-icons/InfoFillSm.tsx
> bug(UIKIT-955,icons,InfoFillSm): Исправлена чрезмерная оптимизация

- packages/form/src/FormMobilePhoneField/FormMobilePhoneField.tsx
> bug(UIKIT-951,form,FormMobilePhoneField): Поправил отображение маски

- packages/components/src/theme/components/MuiAutocomplete.ts
> bug(UIKIT-967,ui,autocomplete): Размер иконок приведен в соответствие с макетом

- packages/form/src/FormCheckbox/FormCheckbox.tsx
> bug(UIKIT-977,form,FormCheckbox): Title стал опциональный

- packages/components/src/TextField/TextField.stories.tsx
- packages/components/src/TextField/TextField.test.tsx
- packages/components/src/TextField/TextField.tsx
- packages/components/src/theme/components/MuiAutocomplete.ts
> feat(UIKIT-846,ui,TextField): Добавлены startAdornment и endAdornment props

- packages/components/src/theme/palette/brandPalette.ts
- packages/components/src/theme/palette/palette.ts
> feat(UIKIT-756,theme): Добавить отдельную продуктовую палитру

- packages/components/src/DataGrid/DataGridCell/DataGridCell.tsx
- packages/components/src/TextArea/TextArea.stories.tsx
> feat(UIKIT-802,ui,TextArea): Реализует storybook

- packages/components/src/MenuItem/MenuItem.stories.tsx
- packages/components/src/MenuItem/MenuItem.tsx
- packages/components/src/theme/components/MuiMenuItem.ts
> feat(UIKIT-980,ui,MenuItem): Изменено отображение состояния selected

- packages/components/src/MaskField/MaskField.stories.tsx
- packages/form/src/FormMaskField/FormMaskField.stories.tsx
> feat(UIKIT-798,ui,MaskField): Реализует storybook

- README.md
> build(UIKIT-968,ui,theme): Перезапуск релиза

- package-lock.json
- packages/icons/package.json
> bug(UIKIT-1018,Icons): Фикс зависимостей для Icons

- packages/components/src/DropdownButton/DropdownButton.stories.tsx
- packages/components/src/DropdownButton/DropdownButton.tsx
> feat(UIKIT-1022,ui,DropdownButton): Добавлен props popoverProps

- packages/components/src/ConfigProvider/ConfigProvider.tsx
- packages/components/src/PersonalData/PersonalData.stories.tsx
- packages/components/src/PersonalData/PersonalData.test.tsx
- packages/components/src/PersonalData/PersonalData.tsx
- packages/components/src/PersonalData/index.ts
- packages/components/src/index.ts
> feat(UIKIT-937,ui,PersonalData): Новый компонент скрытия перс данных от трекеров

- packages/components/src/Checkbox/styles.ts
> feat(UIKIT-653,ui,Checkbox): Увеличение размера иконки

- packages/components/src/PageHeader/ButtonGroup/ButtonGroup.tsx
- packages/components/src/PageHeader/ButtonGroup/ButtonGroupMainActions/ButtonGroupMainActions.tsx
- packages/components/src/PageHeader/ButtonGroup/ButtonGroupMainActions/index.ts
- packages/components/src/PageHeader/ButtonGroup/ButtonGroupSecondaryActions/ButtonGroupSecondaryActions.tsx
- packages/components/src/PageHeader/ButtonGroup/ButtonGroupSecondaryActions/index.ts
- packages/components/src/PageHeader/PageHeader.stories.tsx
> feat(UIKIT-1038,ui,PageHeader/ButtonGroup): Добавлена поддержка DropdownButton

- packages/components/src/DatePicker/DatePicker.test.tsx
- packages/components/src/DatePicker/DatePickerInput/DatePickerInput.tsx
> bug(UIKIT-1041,ui,DatePicker): Исправлен баг с появлением popover при disabled

- packages/components/src/index.ts
> bug(UIKIT-1052,ui,StepSlider): Добавлен экспорт из пакета components

- packages/components/src/StepSlider/StepSlider.tsx
> bug(UIKIT-1054,ui,StepSlider): Удален return type у компонента

- package-lock.json
- packages/components/src/Placeholder/styles.ts
> feat(UIKIT-1057,ui,Placeholder): Изменены стили для Placeholder

- packages/components/src/DashboardLayout/DashboardLayout.stories.tsx
- packages/components/src/DashboardLayout/Header/Header.stories.tsx
- packages/components/src/DashboardLayout/Main/Main.stories.tsx
- packages/components/src/DashboardLayout/Sidebar/Sidebar.stories.tsx
> bug(UIKIT-1079,ui,DashboardLayout): Исправлена высота блоков в stories

- packages/components/src/DatePicker/DatePicker.stories.tsx
- packages/components/src/DatePicker/DatePicker.test.tsx
- packages/components/src/DatePicker/DayPicker/DayPicker.tsx
- packages/components/src/DatePicker/DayPicker/hooks/useDaysGrid/useDaysGrid.ts
- packages/components/src/DatePicker/MonthPicker/MonthPicker.tsx
- packages/components/src/DatePicker/MonthPicker/hooks/useMonthsGrid/useMonthsGrid.ts
- packages/components/src/DatePicker/YearPicker/YearPicker.tsx
- packages/components/src/DatePicker/YearPicker/hooks/useYearsGrid/useYearsGrid.ts
- packages/components/src/DatePicker/types/gridBuilder.ts
- packages/components/src/DatePicker/utils/buildGridItem/buildGridResult.ts
> bug(UIKIT-1026,ui,DatePicker): Делает выбор месяца разблокированым

- packages/components/src/SideDialog/SideDialog.tsx
> bug(UIKIT-1109,ui,SideDialog): Исключено свойство anchor

- package-lock.json
- packages/components/src/theme/components/MuiDrawer.ts
- packages/components/src/theme/components/components.ts
> bug(UIKIT-1112,ui,SideDialog): Устанавливает цвет фона из макета

- packages/components/src/Badge/Badge.stories.tsx
> doc(UIKIT-927,components,Badge): Реализован storybook

- packages/components/src/Description/Description.stories.tsx
> doc(UIKIT-929,components,Description): Изменение storybook

- packages/components/src/DashboardLayout/Header/Header.tsx
…ildren
- [x ] Проверить код на соответствие [style guide](https://track.astral.ru/soft/wiki/display/FG/Style+guide)
> feat(UIKIT-1034,components,DashboardLayout.Header): Добавлен props children

- packages/components/src/Select/Select.tsx
- [ x] Проверить код на соответствие [style guide](https://track.astral.ru/soft/wiki/display/FG/Style+guide)
> bug(UIKIT-882,components,Select): Исправлен баг с fullwidth

- packages/components/src/DatePicker/DatePickerInput/DatePickerInput.tsx
> bug(UIKIT-1135,DatePicker): Добавлен пропс inputProps

- packages/icons/generated-themed-icons/CertAddOutlineMd.tsx
- packages/icons/generated-themed-icons/CompanyAddOutlineMd.tsx
- packages/icons/generated-themed-icons/index.ts
> feat(UIKIT-1136,icons): Добавлены иконки

- packages/components/src/MenuOrganization/MenuOrganization.test.tsx
- packages/components/src/MenuOrganization/MenuOrganization.tsx
> feat(UIKIT-1139,ui,MenuOrganization): Добавлен флаг для управления рендером

- packages/components/src/Autocomplete/Autocomplete.tsx
> bug(UIKIT-1137,ui,Autocomplete): Поправлена типизация. Добавлена зависимость в useCallback

- packages/components/src/CodeField/CodeField.stories.tsx
- packages/components/src/CodeField/CodeField.test.tsx
- packages/components/src/CodeField/CodeField.tsx
- packages/components/src/CodeField/hooks/useFocusInput/useFocusInput.ts
> feat(UIKIT-1146,form,CodeField): Добален функционал автофокуса в первую ячейку

- packages/components/src/CodeField/CodeField.test.tsx
- packages/components/src/CodeField/CodeField.tsx
- packages/components/src/CodeField/ResendСodeButton/ResendСodeButton.tsx
- packages/components/src/CodeField/hooks/useCodeState/useCodeState.ts
> feat(UIKIT-1145,ui,CodeField): Сбрасывать введенный код при повторной отправке

- packages/components/src/ConfirmDialog/ConfirmDialog.tsx
> bug(UIKIT-1154,ui,ConfirmDialog): Добавил export к ConfirmDialogProps

- packages/components/src/DropdownButton/DropdownButton.tsx
bug(UIKIT-1144,ui,DropdownButton): Добавить selected для Button при открытом меню
> bug(UIKIT-1144,ui,DropdownButton): Добавить selected для Button

- .github/CODEOWNERS
> chore(UIKIT-1156): Обновлен список CODEOWNERS

- packages/icons/generated-themed-icons/AddDocumentOutlineMd.tsx
- packages/icons/generated-themed-icons/index.ts
> feat(UIKIT-1170,icons): Добавлена иконка

- packages/components/src/PasswordField/PasswordField.test.tsx
- packages/components/src/PasswordField/PasswordField.tsx
- packages/components/src/TextField/TextField.test.tsx
> bug(UIKIT-1143,PasswordField): Добавлено использование ref

- packages/components/src/ContentState/ContentState.tsx
> bug(UIKIT-1035, ui, ContentState): Убран required для imgAlt в состоянии ошибки

- package-lock.json
- packages/icons/package.json
> bug(UIKIT-1187, Icons): Зафиксирована версия @mui/material

- packages/components/src/theme/components/MuiButton.ts
> bug(UIKIT-1190,ui,Button): Исправлен цвет фона для состояния disabled

- packages/components/src/BottomDrawer/BottomDrawer.stories.tsx
- packages/components/src/BottomDrawer/BottomDrawer.tsx
- packages/components/src/BottomDrawer/ButtomDrawer.test.tsx
- packages/components/src/BottomDrawer/constants.ts
- packages/components/src/BottomDrawer/index.ts
- packages/components/src/BottomDrawer/styles.ts
- packages/components/src/index.ts
> feat(UIKIT-1183,ui,BottomDrawer): Реализован компонент BottomDrawer

- packages/components/src/PageLayout/PageLayout.tsx
- packages/components/src/PageLayoutContainer/PageLayoutContainer.tsx
> feat(UIKIT-1212,ui,PageLayout): Добавлен className в PageLayoutContainer

- packages/components/src/Product/styles.ts
> feat(UIKIT-1217,ui,Product): Реализован адаптив под мобильные устройства

- changelog/29.01.2024 - 09.02.2024.md
> Добавлены ссылки на jira и storybook

- changelog/29.01.2024 - 09.02.2024.md
> Добавлены якоря

- changelog/29.01.2024 - 09.02.2024.md
> Revert: добавление якоря

- packages/components/src/NavMenu/NavMenuItem/NavMenuItemButton/styles.ts
> bug(UIKIT-1236,ui,NavMenu): Исправлена ошибка stylelint

- packages/components/src/DashboardLayout/DashboardLayout.stories.tsx
- packages/components/src/DashboardLayout/Header/Header.stories.tsx
- packages/components/src/DashboardLayout/Main/Main.stories.tsx
- packages/components/src/DashboardLayout/Sidebar/Sidebar.stories.tsx
> chore(UIKIT-1232,ui,DashboardLayout): Убраны отступы для stories

- packages/components/src/Placeholder/Placeholder.tsx
- packages/components/src/Placeholder/styles.ts
> feat(UIKIT-1123,ui,Placeholder): Правка стилей под макеты и реализация адаптива

- packages/components/src/Alert/Alert.tsx
- packages/components/src/Alert/index.ts
> feat(UIKIT-1262,ui,Alert): Добавлен экспорт типа AlertSeverity

- packages/components/src/theme/baseTheme/baseTheme.ts
- packages/components/src/utils/external.ts
> bug(UIKIT-1260,ui,createTheme): Исправлено расширение темы через options

- package-lock.json
- packages/components/src/DashboardLayout/DashboardLayout.stories.tsx
- packages/components/src/PageAside/styles.ts
- packages/components/src/PageContent/PageContent.tsx
- packages/components/src/PageContent/styles.ts
- packages/components/src/PageLayout/PageLayout.tsx
- packages/components/src/PageLayoutContainer/PageLayoutContainer.tsx
- packages/components/src/PageLayoutContainer/styles.ts
> bug(UIKIT-1265,ui,PageLayout): Контейнер контента занимает 100% высоты

- changelog/12.02.2024 - 25.02.2024.md
> Add changelog 12.02.2024 - 25.02.2024.md

- changelog/12.02.2024 - 25.02.2024.md
> Update changelog 12.02.2024 - 25.02.2024.md

- .gitignore
- changelog/12.02.2024 - 25.02.2024.md
> chore(UIKIT-1174): .DS_STORE добавлен в gitignore

- packages/components/src/ContentState/ContentState.tsx
- packages/components/src/Iframe/Iframe.stories.tsx
- packages/components/src/Iframe/Iframe.test.tsx
- packages/components/src/Iframe/Iframe.tsx
- packages/components/src/Iframe/constants.ts
- packages/components/src/Iframe/index.ts
- packages/components/src/Iframe/styles.ts
- packages/components/src/index.ts
> feat(UIKIT-352,ui,Iframe): Реализован компонент Iframe

- packages/components/src/theme/components/MuiMenuItem.ts
> feat(UIKIT-1269,ui,MenuItem): Добавлен адаптив под мобильные устройства

- packages/components/src/BottomDrawer/styles.ts
- packages/components/src/DashboardLayout/styles.ts
- packages/components/src/SideDialog/styles.ts
- packages/components/src/SwipeableDrawer/styles.ts
> bug(UIKIT-1284,ui): Замена vh единиц на dvh

- packages/components/src/BottomDrawer/styles.ts
- packages/components/src/DashboardLayout/styles.ts
- packages/components/src/SideDialog/styles.ts
- packages/components/src/WelcomeScreen/WelcomeScreen.stories.tsx
- packages/components/src/WelcomeScreen/styles.ts
> bug(UIKIT-1293,ui): Добавлено использование dvh через supports

- packages/components/src/DataList/DataList.stories.tsx
- packages/components/src/DataList/DataList.test.tsx
- packages/components/src/DataList/DataList.tsx
> bug(UIKIT-1279,ui,DataList): Поправлена типизация для поля keyId

- packages/components/src/Typography/styles.ts
> bug(UIKIT-1238,ui,Typography): Исправлен text-transform для варианта button

- packages/components/src/theme/constants.ts
- packages/components/src/theme/palette/brandPalette.ts
> feat(UIKIT-1310,ui,theme): Добавлена цветовая схема EKO

- packages/components/src/ListItemIcon/styles.ts
> bug(UIKIT-1311,ui,ListItemIcon): Поправлен цвет иконки при hover и selected

- packages/components/src/theme/palette/palette.ts
> bug(UIKIT-1316,ui,theme): Возвращен contrastText в warning, success, error

- packages/components/src/theme/palette/palette.ts
> bug(UIKIT-1316,ui,theme): Возвращает оттенки light,main,dark для warning,success,error

- changelog/26.02.2024 - 15.03.2024
> Add changelog 26.02.2024 - 15.03.2024

- changelog/26.02.2024 - 15.03.2024.md
> Add changelog 26.02.2024 - 15.03.2024.md

- packages/components/src/Profile/Profile.tsx
- packages/components/src/hooks/useMenu/useMenu.ts
Задача
https://track.astral.ru/soft/browse/UIKIT-658
> bug(UIKIT-658,ui,Profile): Исправлено размер popover не соответствует длине кнопки

- packages/components/src/theme/baseTheme/baseTheme.ts
- packages/components/src/theme/palette/palette.ts
> bug(UIKIT-1314,ui,theme): Убран вывод ошибки в консоль для цвета info

- packages/components/src/Description/Name/Name.tsx
> bug(UIKIT-1149,ui,Description): Убрано двоеточие когда leader равен true

- packages/components/src/NavMenu/Item/ItemButton/styles.ts
> bug(UIKIT-1315,ui,NavMenu): Исключен проброс пропса isGroupTitleItem в DOM

- packages/components/src/styles/styled.ts
- packages/features/src/cryproPro/components/CryptoProProvider/CryptoProProvider.tsx
> bug(UIKIT-1329,features,CryptoProProvider): Скрыл нативное модально окно от КриптоПро

- packages/components/src/Avatar/styles.tsx
До этого текст мог соприкасаться с границами аватара.
> bug(UIKIT-1343,ui,Avatar): Поправлен размер шрифта для мобильной версии

- packages/components/src/Tag/styles.ts
До этого был цвет gray-100, теперь gray-300
> bug(UIKIT-1318,ui,Tag): Поправлен цвет removable тега

- packages/components/src/WelcomeScreen/WelcomeScreen.stories.tsx
- packages/components/src/WelcomeScreen/WelcomeScreen.test.tsx
- packages/components/src/WelcomeScreen/WelcomeScreen.tsx
- packages/components/src/WelcomeScreen/hooks/useLogic/useLogic.ts
> feat(UIKIT-1355,ui,WelcomeScreen): Добавлен пропс isSuccess

- package-lock.json
- packages/components/src/FeedbackPanel/FeedbackPanel.stories.tsx
- packages/components/src/FeedbackPanel/FeedbackPanel.tsx
- packages/components/src/FeedbackPanel/styles.ts
> bug(UIKIT-1357,ui,FeedbackPanel): Исправлена ошибка отображения FeedbackPanel

- packages/components/src/Notification/Notification.tsx
- packages/components/src/Notification/types.ts
- packages/components/src/index.ts
> feat(UIKIT-1306,ui,Notify): Добавлен экспорт типа для использования в классах

- packages/components/src/Autocomplete/Autocomplete.stories.tsx
- packages/components/src/Autocomplete/Autocomplete.test.tsx
- packages/components/src/Autocomplete/Autocomplete.tsx
- packages/form/src/FormAutocomplete/FormAutocomplete.stories.tsx
- packages/form/src/FormAutocomplete/FormAutocomplete.test.tsx
- packages/form/src/FormAutocomplete/FormAutocomplete.tsx
До этого кнопка "очистить" отображалась постоянно.
> bug(UIKIT-1115,ui,Autocomplete): Добавлено сокрытие кнопки очистки при пустом инпуте

- changelog/18.03.2024 - 29.03.2024.mdx
> Add changelog 18.03.2024 - 29.03.2024

- changelog/18.03.2024 - 29.03.2024.mdx
> Update changelog 18.03.2024 - 29.03.2024

- packages/components/src/TextField/TextField.stories.tsx
- packages/components/src/TextField/TextField.test.tsx
- packages/components/src/TextField/TextField.tsx
> feat(UIKIT-1129,ui,TextField): Добавлен проп maxLength

- packages/components/src/index.ts
> bug(UIKIT-1378,ui,Notification): Добавлен экспорт всех сущностей из Notification

- packages/components/src/index.ts
> bug(UIKIT-1385,ui,Link): Добавлен реэкспорт для компонента Link

- packages/components/src/DatePicker/DateCalendar/styles.tsx
> bug(UIKIT-1398,DatePicker): Убрана фиксация размеров календаря

- changelog/01.04.2024 - 13.04.2024.md
> Add changelog 01.04.2024 - 13.04.2024.md

- packages/components/src/Placeholder/styles.ts
> bug(UIKIT-1425,Placeholder): Исправлен отступ от заголовка

- packages/components/src/CheckableTag/styles.ts
- packages/components/src/Tag/Tag.stories.tsx
- packages/components/src/Tag/Tag.tsx
- packages/components/src/Tag/styles.ts
> feat(UIKIT-1364,Tag): Изменены цвета в соответствии с дизайн-системой

- packages/components/src/DataGridInfinite/DataGridInfinite.tsx
- packages/components/src/DataGridInfinite/styles.ts
> bug(UIKIT-1426,DataGridInfinite): Убрана минимальная высота

- packages/components/src/Autocomplete/Autocomplete.stories.tsx
- packages/components/src/Autocomplete/Autocomplete.tsx
> feat(UIKIT-1197, Autocomplete): Изменен дефолтный текст ошибки

- packages/components/src/DataGrid/DataGridCell/DataGridCell.tsx
- packages/components/src/DataGrid/DataGridCell/styles.ts
- packages/components/src/DataGrid/DataGridHeadColumn/styles.ts
- packages/components/src/DataGrid/styles.ts
> feat(UIKIT-1273,DataGrid): Изменены отступы для ячеек

- packages/components/src/PageLayout/PageLayout.tsx
> bug(UIKIT-1440, PageLayout): Поправлена типизация для backButton, теперь учитывает свойства component

- .github/workflows/publish_changelog.yml
> chore(UIKIT-1442): Настройка ci для генерации changelog

- packages/components/src/PageHeader/ButtonGroup/ButtonGroup.tsx
- packages/components/src/PageHeader/ButtonGroup/ButtonGroupMainActions/ButtonGroupMainActions.tsx
- packages/components/src/PageHeader/ButtonGroup/ButtonGroupSecondaryActions/ButtonGroupSecondaryActions.tsx
- packages/components/src/PageHeader/PageHeader.tsx
- packages/components/src/PageLayout/PageLayout.tsx
> bug(UIKIT-1441, PageLayout): Поправлена типизация для actions, теперь  учитывает свойства component

- packages/components/src/Description/Description.stories.tsx
- packages/components/src/Description/Value/Value.tsx
> bug(UIKIT-1455,Description): Исправлено отображение пустого значения

- .github/workflows/chagelog_telegram_notify.yml
- .github/workflows/changelog_generate.yml
- changelog-generator/package.json
- changelog-generator/src/changelogGenerate.ts
- changelog-generator/src/services/FileService/FileService.ts
- changelog-generator/src/services/MarkdownService/MarkdownService.ts
- changelog-generator/src/telegramNotify.ts
- changelog-generator/src/utils/generateLinkToStorybook/generateLinkToStorybook.ts
> chore(UIKIT-1463): Разделение генерации чейнжлога и публикации новости на разные процессы

- lint-staged.config.js
- packages/components/src/NotificationNext/NotificationStackContainerNext/styles.ts
> feat(UIKIT-1459, NotificationNext): Доработано отображение кнопки закрытия уведомлений

- packages/ui/pack.js
- packages/ui/src/next.ts
> build(UIKIT-1470): Добавлена секция next, для @astral/ui для компонентов с требованием react >= 18 версии

- packages/components/package.json
- packages/ui/package.json
> build(UIKIT-1470): Исправлено добавление секции next, для @astral/ui

- commitlint.config.js
1. В список разрешенных префиксов задач добавлен префикс SHRD
2. Удален проброс перечня scope
> chore(SHRD-36): Изменена конфигурация для commitlint

- packages/components/src/Tooltip/Tooltip.tsx
- packages/components/src/Tooltip/styles.tsx
> feat(UIKIT-1453,Tooltip): Изменен отступ от элемента

- package-lock.json
- packages/components/package.json
- packages/components/src/Skeleton/Skeleton.stories.tsx
- packages/components/src/Skeleton/Skeleton.tsx
- packages/components/src/Skeleton/index.ts
- packages/components/src/Skeleton/styles.ts
- packages/components/src/index.ts
- packages/components/src/utils/colors/index.ts
- packages/components/src/utils/colors/rgba/index.ts
- packages/components/src/utils/colors/rgba/rgba.test.ts
- packages/components/src/utils/colors/rgba/rgba.ts
> feat(UIKIT-1261,Skeleton): Реализован компонент Skeleton

- packages/form/src/FormAutocomplete/FormAutocomplete.stories.tsx
- packages/form/src/FormAutocomplete/FormAutocomplete.test.tsx
- packages/form/src/FormAutocomplete/FormAutocomplete.tsx
> bug(UIKIT-1507,FormAutocomplete): Исправлено отображение 'undefined' в input, если value отсутствует

- packages/form/src/FormEmailField/FormEmailField.stories.tsx
- packages/form/src/FormEmailField/FormEmailField.test.tsx
- packages/form/src/FormEmailField/FormEmailField.tsx
- Добавлена story про trim
- Написаны тесты на trim
> refactor(UIKIT-1507,FormEmailField): Компонент стал использовать EmailField вместо TextField

- packages/components/src/RadioCard/RadioCard.tsx
- packages/components/src/RadioGroup/RadioGroup.tsx
- packages/components/src/StepSlider/StepSlider.tsx
- packages/components/src/hooks/useId/index.ts
- packages/components/src/hooks/useId/useId.ts
> bug(UIKIT-1502): Заменена реализация хука useId для RadioCard, RadioGroup, StepSlider

- packages/components/src/Iframe/Iframe.test.tsx
- packages/components/src/Iframe/Iframe.tsx
> bug(UIKIT-1516,Iframe): Исправлена проблема отсутствия возможности отключить политики sandbox

- packages/components/src/NotificationNext/NotificationStackContainerNext/useLogic/useLogic.ts
> bug(UIKIT-1518,NotificationNext): Поправлено отображение кнопки после ручного закрытия всех уведомлений

- packages/components/src/SearchField/SearchField.test.tsx
- packages/components/src/SearchField/SearchField.tsx
> bug(UIKIT-1536,SearchField): Устанавливает фокус при клике по иконкам

- packages/components/src/Description/Description.stories.tsx
- packages/components/src/Description/Description.tsx
- packages/components/src/Description/Name/styles.ts
- packages/components/src/Description/Value/Value.tsx
- packages/components/src/Description/styles.ts
> refactor(UIKIT-1512,Description): Заменены теги на семантически верные

- packages/components/src/Description/Description.stories.tsx
- packages/components/src/Description/Value/Value.tsx
- packages/components/src/Description/Value/styles.ts
> bug(UIKIT-1540,Description): Убраны отступы у dd

- packages/components/src/Typography/Typography.stories.tsx
- packages/components/src/Typography/Typography.tsx
> bug(UIKIT-1548,Typography): Добавлен variant=inherit в типы

- packages/components/src/PageHeader/PageHeader.stories.tsx
- packages/components/src/PageHeader/styles.ts
> bug(UIKIT-1546,PageHeader): Исправлена проблема переполнения контейнера заголовка страницы

- packages/components/src/Tree/MultipleTreeList/MultipleTreeList.stories.tsx
- packages/components/src/Tree/MultipleTreeList/MultipleTreeList.test.tsx
- packages/components/src/Tree/MultipleTreeList/MultipleTreeList.tsx
- packages/components/src/Tree/MultipleTreeList/TreeItem/TreeItem.tsx
- packages/components/src/Tree/MultipleTreeList/TreeItem/useLogic/useLogic.ts
- packages/components/src/Tree/MultipleTreeList/TreeItem/useLogic/utils/getAllChildrenId/getAllChildrenId.ts
- packages/components/src/Tree/MultipleTreeList/types.ts
- packages/components/src/Tree/TreeItem/TreeItem.tsx
- packages/components/src/Tree/TreeItem/useLogic/useLogic.ts
- packages/components/src/Tree/TreeList/TreeItem/TreeItem.tsx
- packages/components/src/Tree/TreeList/TreeItem/useLogic/useLogic.ts
- packages/components/src/Tree/TreeList/TreeList.stories.tsx
- packages/components/src/Tree/TreeList/TreeList.test.tsx
- packages/components/src/Tree/TreeList/TreeList.tsx
- packages/components/src/Tree/TreeList/types.ts
- packages/components/src/Tree/index.ts
- packages/components/src/Tree/types.ts
- packages/components/src/index.ts
> feat(UIKIT-1552,TreeList): Добавлена возможность раскрывать дерево по умолчанию

- packages/components/src/Tree/MultipleTreeList/MultipleTreeList.stories.tsx
- packages/components/src/Tree/MultipleTreeList/MultipleTreeList.test.tsx
- packages/components/src/Tree/MultipleTreeList/TreeItem/TreeItem.tsx
- packages/components/src/Tree/MultipleTreeList/TreeItem/useLogic/useLogic.ts
- packages/components/src/Tree/MultipleTreeList/TreeItem/useLogic/utils/getAllChildrenId/getAllChildrenId.ts
- packages/components/src/Tree/MultipleTreeList/types.ts
- packages/components/src/Tree/TreeItem/TreeItem.tsx
- packages/components/src/Tree/TreeItem/styles.ts
- packages/components/src/Tree/TreeList/TreeItem/TreeItem.tsx
- packages/components/src/Tree/TreeList/TreeItem/useLogic/useLogic.ts
- packages/components/src/Tree/TreeList/TreeList.stories.tsx
- packages/components/src/Tree/TreeList/types.ts
- packages/components/src/Tree/index.ts
> feat(UIKIT-1576,TreeList): Добавлена возможность блокировки элементов дерева

- packages/components/src/Description/Description.stories.tsx
> doc(SHRD-39,Description): Добавлена ссылка на ui guide

- packages/components/src/NotificationNext/NotificationContainerNext/styles.ts
- packages/components/src/NotificationNext/types.ts
> bug(UIKIT-1568,NotificationNext): ToastId добавлен в типы. Исправлены анимации уведомлений

- packages/components/src/Product/styles.ts
> feat(UIKIT-1228,Product): Убраны состояния, изменен fontWeight

- packages/components/src/FlowButton/FlowButton.stories.tsx
- packages/components/src/FlowButton/FlowButton.tsx
- packages/components/src/FlowButton/styles.ts
> feat(UIKIT-1366,FlowButton): Добавлен вариант без targetText

- packages/components/src/DescriptionList/DescriptionList.stories.tsx
- packages/components/src/DescriptionList/DescriptionList.tsx
> feat(UIKIT-1584,DescriptionList): Изменена типизация color

- packages/components/src/Switch/Switch.tsx
- packages/components/src/Switch/styles.ts
> bug(UIKIT-1582,Switch): Добавлено состояние фокуса

- packages/components/src/DataGrid/DataGridRow/DataGridRow.tsx
- packages/components/src/DataGrid/DataGridRow/styles.ts
- packages/components/src/Table/TableCell/TableCell.tsx
- packages/components/src/Table/TableCell/styles.ts
> bug(UIKIT-1598,DataGrid): Исправлен отступ чекбоксов в заблокированных ячейках

- packages/components/src/PageHeader/ButtonGroup/ButtonGroupSecondaryActions/ButtonGroupSecondaryActions.tsx
> bug(UIKIT-1597,PageHeader): Поправлена типизация для secondary actions

- packages/components/src/Description/Name/Name.tsx
- packages/components/src/Description/Name/styles.ts
> bug(UIKIT-1603,Description): Убран leader на мобильных устройствах

- packages/components/src/ListItemButton/ListItemButton.tsx
- packages/components/src/PageHeader/ButtonGroup/ButtonGroupSecondaryActions/ButtonGroupSecondaryActions.tsx
- packages/components/src/PageHeader/PageHeader.stories.tsx
> feat(UIKIT-1623,PageHeader): Добавлен Tooltip для ButtonGroupSecondaryActions

- packages/components/src/DataGrid/DataGrid.stories.tsx
- packages/components/src/DataGridPagination/DataGridPagination.test.tsx
- packages/components/src/DataGridPagination/DataGridPagination.tsx
- packages/components/src/DataGridPagination/constants.ts
- packages/components/src/DataGridPagination/styles.ts
- packages/components/src/DataGridPagination/useLogic/index.ts
- packages/components/src/DataGridPagination/useLogic/useLogic.ts
> feat(UIKIT-1439,DataGridPagination): Добавлена возможность настройки количества выводимых элементов на странице

- packages/components/src/Tooltip/styles.tsx
> bug(UIKIT-1600,Tooltip): Изменен отступ от элемента

- packages/components/src/PageHeader/ButtonGroup/ButtonGroupSecondaryActions/ButtonGroupSecondaryActions.tsx
> bug(UIKIT-1631,PageHeader): Изменена позиция тултипа для ButtonGroupSecondaryActions

- packages/components/src/Dialog/Dialog.tsx
- packages/components/src/Dialog/styles.ts
- packages/components/src/theme/components/MuiDialog.ts
> bug(UIKIT-1550,Dialog): Исправлена анимация закрытия Dialog

- packages/components/src/Menu/Menu.stories.tsx
- packages/components/src/MenuGroup/MenuGroup.stories.tsx
- packages/components/src/MenuItem/MenuItem.stories.tsx
- packages/components/src/MenuList/MenuList.stories.tsx
- packages/components/src/NavMenu/NavMenu.stories.tsx
- packages/components/src/NotificationList/NotificationList.stories.tsx
- packages/components/src/PageHeader/PageHeader.stories.tsx
- packages/components/src/PageLayout/PageLayout.stories.tsx
- packages/components/src/Paper/Paper.stories.tsx
- packages/components/src/Product/Product.stories.tsx
- packages/components/src/Profile/Profile.stories.tsx
- packages/components/src/ProgressBar/ProgressBar.stories.tsx
- packages/components/src/RadioCard/RadioCard.stories.tsx
- packages/components/src/Rating/Rating.stories.tsx
- packages/components/src/Slide/Slide.stories.tsx
- packages/components/src/Stepper/Stepper.stories.tsx
- packages/components/src/SwipeableDrawer/SwipeableDrawer.stories.tsx
- packages/components/src/Switch/Switch.stories.tsx
- packages/components/src/TagBadge/TagBadge.stories.tsx
- packages/components/src/ToggleButton/ToggleButton.stories.tsx
- packages/components/src/ToggleButtonGroup/ToggleButtonGroup.stories.tsx
- packages/components/src/WelcomeScreen/WelcomeScreen.stories.tsx
> doc(UIKIT-1480): Переформатирован storybook в новый формат

- packages/components/src/NewDataGrid/Cell/styles.ts
> bug(UIKIT-1646,NewDataGrid): Исправлено растягивание ячейки по горизонтали при переполнении

- packages/components/src/PageHeader/styles.ts
> bug(UIKIT-1644,PageHeader): Добавлен отступ в header

- packages/components/src/Filename/Filename.stories.tsx
- packages/components/src/Filename/styles.ts
> bug(UIKIT-1645,Filename): Убран отступ у Filename

- packages/components/src/DashboardLayout/Sidebar/Sidebar.tsx
> bug(UIKIT-1636,DashboardLayout): Добавлен className для Sidebar

- packages/components/src/NavMenu/Item/ItemButton/styles.ts
> bug(UIKIT-1637,NavMenu): Поправлен цвет фона selected элемента при наведении

- packages/icons/generated-themed-icons/ClockFillSm.tsx
- packages/icons/generated-themed-icons/index.ts
- packages/icons/themed-assets/clock-fill-sm.svg
> feat(UIKIT-1642,Icon): Добавлена иконка ClockFillSm

- packages/components/src/DescriptionCell/DescriptionCell.stories.tsx
> bug(UIKIT-1658,DescriptionCell): Исправлена example story

- packages/components/src/Badge/Badge.stories.tsx
> doc(UIKIT-1619,Badge): Добавлена story с anchorOrigin

- packages/components/src/DialogActions/DialogActions.tsx
- packages/components/src/DialogActions/styles.ts
- packages/components/src/DialogContent/styles.ts
> feat(UIKIT-1672,Dialog): Добавлен отступ для DialogContent

- packages/components/src/NewDataGrid/Head/Head.tsx
- packages/components/src/NewDataGrid/Head/useLogic/useLogic.tsx
- packages/components/src/NewDataGrid/NewDataGrid.stories.tsx
- packages/components/src/NewDataGrid/NewDataGrid.test.tsx
- packages/components/src/NewDataGrid/Row/Row.tsx
- packages/components/src/NewDataGrid/faker.ts
- packages/components/src/NewDataGrid/types.ts
- packages/components/src/NewDataGrid/useLogic/useLogic.tsx
- packages/components/src/NewDataGridInfinite/NewDataGridInfinite.stories.tsx
- packages/components/src/NewDataGridInfinite/NewDataGridInfinite.test.tsx
- packages/components/src/NewDataGridInfinite/NewDataGridInfinite.tsx
- packages/components/src/NewDataGridInfinite/faker.ts
- packages/components/src/NewDataGridInfinite/useLogic/useLogic.ts
> feat(UIKIT-1476,NewDataGrid): Добавлена опциональность выборки

- packages/components/src/index.ts
> feat(UIKIT-1681,NewDataGrid): Добавлен экспорт типа NewDataGridColumns

- packages/components/src/NewDataGrid/Row/NestedChildren/NestedChildren.tsx
> bug(UIKIT-1683,NewDataGrid): Исправлена ошибка семантики для вложенного Collapse

- packages/components/src/Description/Description.stories.tsx
- packages/components/src/Description/Description.tsx
- packages/components/src/Description/DescriptionContext/DescriptionContext.tsx
- packages/components/src/Description/DescriptionContext/DescriptionContextProvider/DescriptionContextProvider.tsx
- packages/components/src/Description/Value/Value.tsx
- packages/components/src/Description/Value/styles.ts
- packages/components/src/Description/constants.ts
- packages/components/src/Description/styles.ts
- packages/components/src/Description/useLogic/index.ts
- packages/components/src/Description/useLogic/useLogic.ts
> feat(UIKIT-1608,Description): Реализован адаптив под мобильные устройства

- packages/components/src/PageHeader/PageHeader.stories.tsx
- packages/components/src/PageHeader/PageHeader.tsx
> bug(UIKIT-1564,PageHeader): Исправлена семантика

- packages/components/src/DatePicker/DatePicker.stories.tsx
- packages/components/src/DatePicker/DatePicker.test.tsx
- packages/components/src/DatePicker/DatePicker.tsx
- packages/components/src/DatePicker/DatePickerInput/DatePickerInput.tsx
- packages/components/src/DateRangePicker/DateRangePicker.stories.tsx
- packages/components/src/DateRangePicker/DateRangePicker.tsx
> feat(UIKIT-1659,DatePicker): Добавлен пропс startAdornment

- packages/components/src/PageHeader/ButtonGroup/ButtonGroupSecondaryVisibleActions/ButtonGroupSecondaryVisibleActions.tsx
- packages/components/src/PageHeader/PageHeader.test.tsx
> bug(UIKIT-1691,PageHeader): Исправлена работа onClick у SecondaryVisibleAction

- packages/components/src/PageHeader/ButtonGroup/ButtonGroupMainActions/ButtonGroupMainActions.tsx
- packages/components/src/PageHeader/ButtonGroup/ButtonGroupSecondaryVisibleActions/ButtonGroupSecondaryVisibleActions.tsx
> bug(UIKIT-1692,PageHeader): Исправлена передача ключей у действий PageHeader

- packages/components/src/NavMenu/Item/Item.tsx
- packages/components/src/NavMenu/NavMenu.tsx
> bug(UIKIT-1693,NavMenu): Добавлен проброс специфичных пропсов для component и поправлена типизация

- packages/components/src/NewDataGrid/Cell/useLogic/useLogic.ts
- packages/components/src/NewDataGrid/NewDataGrid.stories.tsx
- packages/components/src/NewDataGrid/NewDataGrid.test.tsx
- packages/components/src/NewDataGrid/NewDataGrid.tsx
- packages/components/src/NewDataGrid/constants.ts
- packages/components/src/NewDataGrid/faker.ts
> feat(UIKIT-309,NewDataGrid): Добавлена обработка emptyCellValue

- packages/components/src/Description/Value/styles.ts
> bug(UIKIT-1697,Description): Исправлено попадание проса в DOM

- packages/components/src/ActionCell/ActionCell.stories.tsx
- packages/components/src/ActionCell/ActionCell.test.tsx
- packages/components/src/ActionCell/ActionCell.tsx
- packages/components/src/ActionCell/MainAction/MainAction.tsx
- packages/components/src/ActionCell/SecondaryAction/SecondaryActions.tsx
- packages/components/src/ActionCell/useLogic/index.ts
- packages/components/src/ActionCell/useLogic/useLogic.ts
> feat(UIKIT-1694,ActionCell): Добавлены блокирующие операции

- package-lock.json
- packages/components/package.json
> bug(UIKIT-1702): Повышена версия пакета remeda, до версии, содержащей функцию uniqueBy

- packages/components/src/Description/Value/Value.tsx
> bug(UIKIT-1701,Description): Отменено всплытие события нажатия при копировании текста

- packages/form/src/FormAutocomplete/FormAutocomplete.tsx
> bug(UIKIT-1708,FormAutocomplete): Поправлена типизация onChange

- packages/components/src/hooks/index.ts
- packages/components/src/hooks/useViewportType/useViewportType.stories.tsx
> feat(UIKIT-1717,ui,hooks): Добавлен экспорт useViewportType

- packages/components/src/Tag/styles.ts
> bug(UIKIT-1719,TagBadge): Исправлено применение цвета к TagBadge

- packages/icons/generated-themed-icons/SuccessFillSm.tsx
> bug(UIKIT-1736,Icons): Исправлен path для SuccessFillSm

- packages/components/src/SideDialog/SideDialog.stories.tsx
- packages/components/src/SideDialog/SideDialog.tsx
- packages/components/src/SideDialog/constants.ts
- packages/components/src/SideDialog/styles.ts
> feat(UIKIT-625,SideDialog): Добавлен пропс size

- packages/components/src/DialogContent/styles.ts
> feat(UIKIT-1724,DialogContent): Поправлены отступы для мобильных устройств

- packages/components/src/CodeField/styles.ts
> feat(UIKIT-1730,CodeField): Реализована адаптация под мобильные устройства

- packages/components/src/NewDataGrid/Body/styles.tsx
- packages/components/src/NewDataGrid/styles.ts
> bug(UIKIT-1738,NewDateGrid): Поправлена работа скрола для содержимого таблицы

- packages/components/src/Paper/Paper.stories.tsx
- packages/components/src/theme/components/MuiPaper.ts
> feat(UIKIT-1737,Paper): Поправлены стили для варианта outlined

- packages/components/src/NewDataGrid/NewDataGrid.stories.tsx
- packages/components/src/NewDataGrid/Row/Row.tsx
> bug(UIKIT-1740,NewDataGrid): Исправлено отсутствие отступа при isNotSelectable

- packages/components/src/DialogActions/styles.ts
- packages/components/src/DialogContent/styles.ts
> feat(UIKIT-1725,Dialog): Исправлены отступы мобильной версии

- packages/components/src/AutoSaveIndicator/AutoSaveIndicator.stories.tsx
> doc(UIKIT-1766,AutoSaveIndicator): Исправлен текст у stories

- packages/components/src/NewDataGrid/Row/useLogic/useLogic.ts
> bug(UIKIT-1755,NewDataGrid): Исправлено отображение тултипа при disabled строки

- packages/components/src/CodeField/CodeField.stories.tsx
- packages/components/src/CodeField/CodeField.tsx
- packages/components/src/CodeField/styles.ts
> bug(UIKIT-1767,CodeField): Исправлен skeleton CodeField

- packages/components/src/NotificationNext/NotificationNext.stories.tsx
- packages/components/src/NotificationNext/NotificationNext.test.tsx
- packages/components/src/NotificationNext/NotificationNext.tsx
- packages/components/src/NotificationNext/NotificationTemplateNext/NotificationTemplateNext.tsx
- packages/components/src/NotificationNext/NotificationTemplateNext/constants.tsx
- packages/components/src/NotificationNext/NotificationTemplateNext/styles.ts
- packages/components/src/NotificationNext/NotificationTemplateNext/utils/getNotificationTemplateStyles/getNotificationTemplateStyles.ts
- packages/components/src/NotificationNext/constants.ts
- packages/components/src/NotificationNext/types.ts
> feat(UIKIT-1259,NotificationNext): Добавлен тип уведомлений progress

- packages/components/src/StaticCalendar/StaticDaysCalendar/StaticDaysCalendar.tsx
- packages/components/src/StaticCalendar/StaticDaysCalendar/useLogic/useLogic.ts
- packages/components/src/utils/date/buildDaysCalendarGrid/buildDaysCalendarGrid.test.ts
- packages/components/src/utils/date/buildDaysCalendarGrid/buildDaysCalendarGrid.ts
> bug(UIKIT-1798,StaticDaysCalendar): Исправлена проблема отображения заблокированных дат

- packages/components/src/PageHeader/PageHeader.tsx
> bug(UIKIT-1780,PageHeader): Уровень заголовка заменен на h1

- packages/components/src/DatePicker/hooks/useDatePickerOptions/useDatePickerOptions.ts
- packages/components/src/DatePicker/useLogic/useLogic.ts
> feat(UIKIT-1726,DatePicker): Поправлена логика работы с промежуточной датой

- packages/components/src/NewDataGridInfinite/NewDataGridInfinite.stories.tsx
- packages/components/src/NewDataGridInfinite/faker.ts
> doc(UIKIT-1602,NewDataGridInfinite): Добавлены story  с блокировкой строк

- packages/components/src/ConfirmAction/ConfirmAction.tsx
- packages/components/src/DataGridActionCell/DataGridActionCell.test.tsx
- packages/components/src/DataGridActionCell/DataGridActionCell.tsx
- packages/components/src/DataGridActionCell/MainAction/MainAction.tsx
- packages/components/src/DataGridActionCell/types.ts
- packages/components/src/NewDataGrid/NewDataGrid.stories.tsx
> feat(UIKIT-1799,DataGridActionCell): Добавлено подтверждение для main действий

- packages/components/src/NotificationNext/NotificationStackContainerNext/useLogic/useLogic.ts
> bug(UIKIT-1800,NotificationNext): Исправлена блокировка части экрана после скрытия уведомлений

- packages/components/src/Description/Description.stories.tsx
- packages/components/src/Description/Value/Value.tsx
- packages/components/src/Description/Value/enums.ts
- packages/components/src/Description/Value/styles.ts
> feat(UIKIT-1784,Description): Заменена логика копирования

- packages/components/src/Description/Value/Value.tsx
- packages/components/src/Description/Value/styles.ts
- packages/components/src/Description/styles.ts
- packages/components/src/DescriptionList/DescriptionList.stories.tsx
- packages/components/src/DescriptionList/DescriptionList.tsx
- packages/components/src/DescriptionList/styles.ts
- packages/components/src/DescriptionList/utils/getTooltipProps/getTooltipProps.ts
- packages/components/src/DescriptionList/utils/getTooltipProps/index.ts
- packages/components/src/DescriptionList/utils/index.ts
> feat(UIKIT-1783,DescriptionList): Добавлен variant guid

- packages/components/src/DatePicker/DatePickerInput/DatePickerInput.tsx
> feat(UIKIT-1741,DatePicker): Добавлен атрибут autocomplete

- packages/components/src/DataGridPagination/DataGridPagination.tsx
- packages/components/src/DataGridPagination/useLogic/useLogic.ts
> bug(UIKIT-1819,DataGridPagination): Исправлено исчезновение футера при переходе между страницами

- packages/components/src/Autocomplete/Autocomplete.tsx
- packages/form/src/FormAutocomplete/FormAutocomplete.test.tsx
> feat(UIKIT-1757,Autocomplete): Добавлено отображение стрелки при freeSolo
