kaluga-astral/frontend

packages/ui/src/Grid/Grid.stories.tsx

там из theme не правильно тянется spacing, идет 4px, вместо 3, поэтому для компонента хелпера только для стори бук было решено оставить просто "3px", забыл дописать 'px', и вместо 3px там сейчас 12px

UI.Grid.Исправление borderRadius item-элемента для отображения в сторибуке

---

packages/ui/package.json

Добавлено поле `exports` в `package.json` пакета `@astral/ui`, что позволяет делать такие импорты:
```
import {
StylesCache,
} from '@astral/ui/server'
```

build: Добавляет экспорт для @astral/ui/server

---

packages/ui/src/Notification/NotificationContainer/NotificationContainer.tsx

Тесты jsdom падают с document is not defined в React компонентах из-за injectStyle в NoficationContainer, было реализована работа injectStyle только в браузере

UIKIT-303: bug(ui,Notification): Использование injectStyle только в браузере

---

packages/ui/src/DataGrid/DataGrid.tsx
packages/ui/src/DataGrid/DataGridHead/DataGridHead.tsx
packages/ui/src/DataGrid/DataGridHeadColumn/DataGridHeadColumn.tsx
packages/ui/src/DataGrid/DataGridHeadColumn/styled.tsx

https://astraltrack.atlassian.net/browse/UIKIT-306
1. onSort теперь не обязательный параметр для DataGrid
2. при sortable: false - курсор дефолтный (ранее всегда был pointer, не важно была ли сортировка или нет)
3. Второй generic SortField теперь не обязательный (ранее нужно или не указывать generic или указать два, даже если нет сортировки в таблице)
4. Исправлена верстка хедера таблицы ближе к дизайну: Увеличен отступ сверху и снизу (а то слишком маленькая строка хедеров) и добавлен серый цвет для заголовков таблицы

UIKIT-306: bug(ui,DataGrid): Исправлена работа таблицы без сортировки

---

packages/ui/src/OverflowTypography/styles.ts

стайлинт выпилил префикс, без которого логика компонента не работает
хотфикс для внезапно пропафшего префикса

bug(UIKIT-327,ui,OverflowTypography): Возврат префикса для OverflowTypography

---

.storybook/themes.js
packages/ui/src/theme/constants.ts
packages/ui/src/theme/palette/brandPalette.ts

Цвета КЭДО повторяют цвето ЭДО, но мало ли когда дизайнерам/PO захочется изменить что то в цветах, чтобы не аффектило цвета ЭДО надо бы создать и использовать для этого отдельную сущность в цветовой палитре

feat(UIKIT-380): добавление цветовой темы KEDO

---

packages/ui/src/theme/palette/palette.ts

Добавил secondary цвет для текста, обычно дизайнеры используют вот этот цвет для подсказок, но это обсуждаемо и можно пообщаться с дизайнерами еще - но пока все дизайнеры в отпуске лучше такой серый, чем черный как сейчас

bug(UIKIT-410,ui,palette): Добавлен secondary цвет для текста

---

packages/ui/src/BackdropStack/services/BackdropStackManager/BackdropStackManager.ts

сейчас крашится на тестах, потому что в окружении ноды нету `document` в глобальной области.
но зато `globalThis` есть и в `nodejs` и в браузере, и в браузере globalThis ссылается на `window` который уже содержит `document`

bug(UIKIT-447,ui,BackdropManager): фолбэк для nodejs окружения

---

packages/ui/src/hooks/index.ts
packages/ui/src/hooks/useForwardedRef/index.ts
packages/ui/src/hooks/useForwardedRef/useForwardedRef.ts
packages/ui/src/index.ts

Дизайн ревью не требуется, чисто технический компонент.
**Что**:
Данный хук является адаптером использования опционального рефа пришедшего сверху, т.к. ForwardedRef может являться колбэком. Это решит проблему совместимости react-hook-form , и forwardedRef в MaskField
**Зачем**:
Текущая реализация MaskField не имеет обертки forwardRef и поэтому кидает варнинг о том что мы забыли сделать это, но если мы оборачиваем реализацию MaskField в forwardRef, то тогда ref из react-hook-form не подходит под нужный нам формат.
**Почему**:
Изначально этот хук был создан в ветке нового ДатаПикера, и я предполагал что в рамках пул реквеста на ДатаПикер этот хук попадет в репозиторий, но с появлением форм, оказалось что им тоже требуется использовать его, для совместимости с последними изменениями по …

feat(UIKIT-470): реализация абстрактного хука useForwardedRef

---

packages/ui/src/DatePicker/MonthPicker/hooks/useMonthsGrid/useMonthsGrid.ts

Если в пикере выбрать 2004й год(или любой где есть зимнее время года), потом выбрать апрель, то по факту будет отрендерен календарь для марта.
Проблема заключается в том что в марте часовой пояс на 1 больше, чем в последующем месяце. Следовательно при добавлении одного месяца нехватает одного часа, и календарь начинает строиться для предыдущего месяца.
Сложно локализуемая проблема, но при этом фикс в 1 строку.

bug(UIKIT-477,ui,Datepicker): Фикс для рендера месяца после зимнего времени

---

packages/ui/src/theme/components/MuiAutocomplete.ts

не стал делать через `styled` потому что там начинаются проблемы с типами.

bug(UIKIT-500,ui,Autocomplete): Обнуление лишнего паддинга в Autocomplete

---

packages/ui/src/DatePicker/DatePicker.tsx
packages/ui/src/DatePicker/hooks/useCalendarNavigate/useCalendarNavigate.ts

https://typeofnan.dev/fix-uncaught-typeerror-destroy-is-not-a-function-in-react/

bug(UIKIT-549,ui,DatePicker): фикс для поддержки реакт 18

---

packages/ui/src/PageHeader/styles.ts

Высота заголовка отличалась для страниц с кнопками и без (у кнопок она 32px)

bug(UIKIT-556,ui,PageHeader): добавлена высота строки для заголовка страницы

---

packages/ui/src/DatePicker/DatePicker.test.tsx
packages/ui/src/DatePicker/DayPicker/hooks/useDaysGrid/useDaysGrid.ts
packages/ui/src/DatePicker/utils/compareDateDayByUTC/compareDateDayByUTC.ts
packages/ui/src/DatePicker/utils/compareDateDayByUTC/index.ts
packages/ui/src/utils/date/isDate/isDate.ts

Если в качестве выбранной используется пограничное значение со смещением по часовому поясу, то выбранным считает следующий день.

bug(UIKIT-585,ui,DatePicker): фикс неправильной проверки на выбранный день

---

packages/components/src/ContentState/ContentState.tsx
packages/components/src/ErrorBoundary/ErrorBoundary.stories.tsx
packages/components/src/ErrorBoundary/ErrorBoundary.tsx
packages/components/src/index.ts

В ErrorBoundary теперь не нужно передавать captureException - он берется из контекста

feat(UIKIT-603,ui,ErrorBoundary): Добавлен экспорт ErrorBoundary

---

packages/components/src/OverflowTypography/hooks/useOverflowed/useOverflowed.ts

`contentRect` возвращает размеры в вещественном виде (с десятыми долями пикселя), а метод дом ноды по получению размеров скрола возвращает округленное значение, отчего появлялись неожиданные срабатывания появления тултипа

bug(UIKIT-607,ui,OverflowTypography): округление для контент рект

---

packages/components/src/CheckableTag/CheckableTag.stories.tsx
packages/components/src/CheckableTag/styles.ts
packages/components/src/Tag/Tag.stories.tsx
packages/components/src/Tag/Tag.tsx
packages/components/src/Tag/constants.ts
packages/components/src/Tag/enums.ts
packages/components/src/Tag/styles.ts
packages/components/src/Tag/types.ts

Реализовано две задачи:
feat(UIKIT-651,ui,Tag): Добавлен тип text для тега
feat(UIKIT-439,ui,Tag): Добавлен пропс размера для тега
size по умолчанию сделан small для обратной совместимости, т.к. изначально теги были реализованы с этой высотой

feat(UIKIT-651,ui,Tag): Добавлены variant="text" и пропс size для тега

---

packages/components/src/DataGrid/DataGrid.stories.tsx
packages/components/src/DataGrid/DataGrid.test.tsx
packages/components/src/DataGrid/DataGrid.tsx
packages/components/src/DataGrid/DataGridLoader/DataGridLoader.tsx
packages/components/src/DataGrid/DataGridLoader/styles.ts
packages/components/src/DataGridPagination/DataGridPagination.test.tsx
packages/components/src/DataGridPagination/DataGridPagination.tsx

@Astral-design Сейчас, если пагинация в таблице не отображается, внизу таблицы показывается полоска. Норм или как-то изменить?

bug(UIKIT-643,ui,DataGridPagination): Футер скрывается на единственной странице

---

packages/components/src/Autocomplete/Autocomplete.test.tsx
packages/components/src/Autocomplete/Autocomplete.tsx
packages/form/src/FormAutocomplete/FormAutocomplete.test.tsx
packages/form/src/FormDatePicker/FormDatePicker.test.tsx
packages/form/src/FormTextField/FormTextField.test.tsx
packages/form/src/hooks/useFormFieldProps/useFormFieldProps.ts

- исправлен inputProps.ref
В компонентах Autocomplete, DatePicker inputProps.ref пробрасывался корректно

bug(UIKIT-682,FormTextField): Не пробрасывается ref

---

packages/components/src/DataGrid/DataGrid.stories.tsx
packages/components/src/theme/components/MuiTableCell.ts

Сейчас, если у строки нет действий (ActionCell), она имеет меньшую высоту, чем строка с действиями. В табличке, где есть оба типа таких строк это смотрится коряво

feat(UIKIT-758,ui,DataGrid): Ячейки приведены к единой начальной высоте 44px

---

package-lock.json
packages/components/package.json

package.json имеет зависимость `"@emotion/cache": "11.7.1"` и используемый `"@mui/material"` так же использует `@emotion/cache`, но немного другой версии. И т.к. у нас версия указана конкретная, без "крышки", мы получаем эффект двух одинаковых плагинов.
решение: использовать схожую версию emotion/cache, и добавить к ней "крышку"

bug(UIKIT-1028,Components): Обновление версии для emotion/cache

---

packages/components/src/CheckboxField/CheckboxField.tsx
packages/components/src/CheckboxField/styles.ts

bug(UIKIT-1017,ui,CheckboxField): Выравнивание лейбла по вертикали относительно чекбокса

---

packages/components/src/CodeField/styles.ts

Маленький фикс, теперь курсор инпута числа будет отображаться ровно по середине.

bug(UIKIT-1368,ui,CodeField): Центрирован инпут числа

---

packages/components/src/Notification/NotificationTemplate/styles.ts

Был добавлен перенос текста, если тестовое содержимое уведомления переполняют контейнер, также пофикшена кнопка, которая при title больше 2 строк начала криво отображаться

bug(UIKIT-1389,ui,Notification): Добавлен перенос текста при переполнении

---

packages/components/src/DashboardLayout/Sidebar/Sidebar.stories.tsx
packages/components/src/NavMenu/Item/Item.tsx
packages/components/src/NavMenu/Item/ItemButton/ItemButton.tsx
packages/components/src/NavMenu/Item/List/List.tsx
packages/components/src/NavMenu/NavMenu.stories.tsx
packages/components/src/OverflowTypography/OverflowTypography.tsx

Для OverflowTypography добавлена возможность указать tooltipProps без title

feat(UIKIT-1634,NavMenu): Добавлена возможность передавать ReactNode в item.text
